# Site Settings
baseurl: ""
url : "https://sb-jang.github.io"

# Blog Settings
theme_settings :
  title : This and That
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/smile.png
    username : Seongbo Jang
    description : Check my CV here. (TBA)
    # experience :
    #   - start : 2017-05-03
    #     end : 2018-05-06
    #     experience : company name, title
    # skills : 
    #   - skill : HTML5 & CSS
    #     value : 85  # Percent value
        
  # Icons
  icons :
    email:  jang.sb@postech.ac.kr # Full email address, e.g. "sample@google.com"
    linkedin:  # Full URL 
    github: sb-jang
    gitlab: 
    bitbucket: 
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram: ssungbo

  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
